---
title: "Vitenskapsteori"
output: html_document
editor_options: 
  chunk_output_type: console
geometry:
  - top=0.5in
  - bottom=0.5in
  - left=1in
  - right=1in
---


Induksjon er en prosess som blir brukt for å trekke konklusjoner basert på observasjoner vi har gjort [@Thuren2022-vp]. Metoden, eller prosessen blir gjerne brukt for å trekke generelle konklusjoner angående hvordan verden er satt sammen og hvordan den fungerer. Konklusjonene baserer seg på spesifikke observasjoner som har blitt gjort tidligere, og observasjonene har gjerne blitt testet om igjen, og om igjen for å sørge for at ting ikke har skjedd ved én tilfeldighet. 

Det finnes både fullstendig og ufullstendig induksjon. Et eksempel på fullstendig induksjon er ved valg, valgresultatet baserer seg på induksjon. Alle stemmesedlene blir telt opp og vi kan konkludere med at kandidaten som har fått flest stemmer, vinner valget. Ved fullstendig induksjon kan vi være helt sikre på at konklusjonen vi har kommet frem til er rett, siden vi har sett på alle stemmesedlene. Ved ufullstendig induksjon baserer man seg på et begrenset antall observasjoner og trekker en generell konklusjon deretter. Ved ufullstendig induksjon vil det alltid være en fare for at konklusjonen er usann, siden man ikke undersøker alle relevante tilfeller. 

Hume mener på sin side at induksjon rett og slett ikke er så mye verdt. I Humes´ øyne er det ingen logisk forklaring til at fremtiden vil fortsette å være lik fortiden i all fremtid. Erfaringer vi har gjort oss tidligere sier heller ikke noe om fremtiden, selv om det gir en god pekepinn. Selv om to biler krasjer i et bestemt kryss i dag, betyr ikke det at to biler vil krasje i det samme krysset i morgen. Hume konkluderer med at induksjon kun er basert på vaner og/eller forventninger og at det ikke er basert på rasjonell grunn. 

En innvendig mot Humes premiss er at vi mennesker klarer å gjøre gode resonnementer, gjenkjenne mønstre og tenke logisk. Med bakgrunn i dette kan vi si at våre forventninger om fremtiden ikke kun er baser på forventninger og vaner, men fra en dypere rasjonell forståelse av verden. At ting har blitt som de har, er et resultat av den stadige evolusjonen og utviklingen vi har hatt som menneskehet. Vi og verden har utviklet oss for å stadig bedre vår overlevelsesevne. Og dermed vil vi også fortsette å utvikle oss videre. 

Hume ville i dette tilfellet antakelig svart med noe som at; selv om vi i all tid så langt har utviklet oss som menneskehet, og verden stadig har tatt fremskritt, betyr det ikke at vi vil fortsette med det i morgen. Selv om all fornuft tyder på at morgendagen vil ligne på dagen i går, siden dagen før der lignet på dagen i går, betyr det ikke at det vil være sånn. Selv om vi mennesker har blitt gode på å kjenne igjen mønstre, kan man fortsatt ikke forutse hvordan morgendagen blir. Det vet vi kun i morgen. 


Hovedessensen av prinsippet om falsifikasjon, eller falsifikasjonisme handler om at vi i vitenskapen ikke bør prøve å finne argumenter for at noe stemmer, men at vi heller bør prøve å falsifisere, altså bevise at noe er usant. Karl Popper var opptatt av at teorier skulle kunne motbevises ved hjelp av eksperimenter, eller observasjoner. Et eksempel vi kan bruke fra idretten er teorien om at bruken av høydetrening kan forbedre utholdenhetsprestasjonen. Hvis man har to forskjellige grupper, en på høydetrening og en uten høydetrening. Og det ikke ses noen forskjell i utholdenhetsprestasjon, kan hypotesen om høydetrening falsifiseres. Hvis teorier kommer seg gjennom mange forsøk på falsifikasjon, kan vi se på den som at den foreløpig er korrekt, men aldri som endelig bekreftet. Popper gikk på sin side så langt, som å si at søken etter bekreftelser på hypoteser er selve kjennetegnet på pseudovitenskap. 

Et problem med falsifikasjonisme, hentet fra idretten er effekten av varmetrening på utholdenhetsprestasjon. Det har i dag blitt vanligere og vanligere å drive med varmetrening, enten i oppvarmet rom eller ved bruk av varmedrakt (for eksempel ullundertøy under regntøy). Det er mye diskutert hva slags effekt dette kan ha på utholdenhetsprestasjonen, også i konkurranser eller tester hvor det er normale forhold (hverken oppvarmet rom eller varmedrakt i bruk). Det er en del andre variabler som spiller inn her, spesielt individuelle forskjeller som gjøres blant utøvere både underveis og i ettertid av en varmetreningsøkt. Eksempler på dette er hydrering underveis og i etterkant, hvile og jern som kosttilskudd. Dette gjør det vanskelig å teste denne hypotesen på en falsifiserbar måte. En mulig løsning på dette problemet er å gjøre lange kontrollerte studier der utøvere gjennomgår trening i varme forhold (varmekammer/varmedrakt), med en stor nok kontrollgruppe som ikke gjør noen form for varmetrening. I tillegg bør man i dette tilfellet sørge for kontrollert oppfølging av både hydrering (sørge for at deltakerne drikker lik mengde), hvile og andre faktorer som kan påvirke effekten av varmetreningen. Dette er ulike tiltak som gjør at hypotesen blir mer falsifiserbar. 

Et annet eksempelproblem innenfor idrettsforskning og falsifikasjonisme er som følger. Det settes opp et prosjekt som skal se på utvikling av utholdenhet og styrke hos en rekke deltakere. Det gjøres baselinetester før en treningsintervensjon på 12 uker. Etter de 12 ukene med trening er gjennomført gjennomføres det nye tester for å se hvordan deltakerne nå presterer. Halve gruppen har trent harde intervaller, og den andre halvdelen har trent rolig trening. Gruppen som har gjennomført intervalltrening har oppnådd mest fremgang, men problemet er at vi ikke har tatt høyde for individuelle forskjeller blant deltakerne som er med. En mulig løsning på dette problemet er at vi lar deltakerne få en 12 ukers washout-periode hvor det ikke blir gjennomført noe trening. Man gjør nye baselinetester for å se om deltakerne nå har mistet treningsadaptasjonene de opparbeidet seg i forkant. Vi gjennomfører nå 12 nye uker med trening, og deltakerne har nå byttet om, de som trente intervalltrening under forrige intervensjon får nå rolig trening denne gangen. På denne måten tar vi høyde for individuelle forskjeller, ettersom vi nå har byttet om på deltakerne. Dette er en måte å gjøre hypotesen mer falsifiserbar på. 

Et tredje forsøk fra idrettsverden er placeboeffekt, det finnes mye forskning gjort på kosttilskudd innenfor idretten. Hvis en utøver tror man får et kosttilskudd som skal gi en forventet bedring i prestasjon kan dette være nok til at man presterer bedre. Dette gjør det vanskelig å falsifisere hypoteser. En mulig løsning på dette problemet er å gjøre double blinded eller dobbeltblinda eksperimenter, så hverken forsker eller forsøksperson vet om man får placebo eller om man får det faktiske kosttilskuddet. Dette gjør hypotesen mer falsifiserbar, for hvis man i dette tilfellet også finner effekt, kan man med ganske god sannsynlighet si at det er på grunn av kosttilskuddets virkemiddel og ikke at utøveren tror man har fått tilskuddet.  


