project:
  type: book

book:
  chapters:
    - index.qmd
    - 01-reliability-tools.qmd
    - 02-regression-models.qmd
    - 03-statistical-inference.qmd
    - 04-study-design.qmd
    - 05-repeated-measurements.qmd
    - 06-vitenskapsteori.qmd
    - 07-laboratory-report.qmd
    - references.qmd

bibliography: resources/bib-final.bib

csl: apa-numeric-superscript.csl

format:
  pdf: 
    keep-tex: true
    latex_engine: xelatex
    mainfont: "Times New Roman"
    sansfont: "Times New Roman"
    monofont: "Courier New"
    include-in-header: 
      text:  |
        \usepackage{amsmath}
        \usepackage{float}
        \usepackage{pdflscape}
        \usepackage{afterpage}
        \usepackage{longtable}
        \usepackage[table]{xcolor}
        \usepackage{longtable}
        \usepackage{booktabs}
        \usepackage{graphicx}
        \usepackage{fontspec}
        \setmainfont{Times New Roman}
        \setsansfont{Times New Roman}
        \setmonofont{Courier New}
    include-before-body:
      text: |
        \begin{titlepage}
        \begin{center}
        \vspace*{1cm}

        {\Huge \textbf{Kvantitativ metode og statistikk (IDR4000)}}

        \vspace{1cm}
        {\Large Kandidatnummer: 505}

        \vspace{1cm}
        Antall ord: \textbf{12874} % Setter inn ordtellingen her

        \vspace{5cm}
        \includegraphics[width=1.6\textwidth]{logo.png}

        \vfill
        {\large 2024-11-22}

        \end{center}
        \end{titlepage}

geometry: 
  - top=0.5in

execute: 
  echo: false 
  warning: false 
  message: false
