---
title: "Summarise"
format: html
editor_options: 
  chunk_output_type: console
---



```{r}

# Set a seed for the random number generator
set.seed(1)
# Generate 10 random numbers from a normal distribution with mean 0 and SD 1
x <- rnorm(10)
# Calculate summary statistics
summary(x)
fivenum(x)
quantile(x)




```



```{r}

library(readxl)
library(tidyverse)
library(ggplot2)
library(dplyr)
library(magrittr)
library(gt)
df <- read_xlsx("data/o2-test.xlsx")

df %>% 
    summarise(minimum = min(vo2.max),
              maksimum = max(vo2.max),
              gjennomsnitt = mean(vo2.max),
              kvartil = quantile(vo2.max),
              standardavvik = sd(vo2.max)) %>% 
  gt()



```




```{r}


x <- c(rnorm(10), NA) 

mean(x)

mean(x, na.rm = TRUE)

```



```{r}



library(exscidata)

cyclingstudy %>% 
  summarise(m = mean(VO2.max, na.rm = TRUE),
            sd = sd(VO2.max, na.rm = TRUE)) %>% 
    gt() %>% 
  fmt_number(columns = m,
             decimals = 0) %>% 
  fmt_number(columns = sd,
             decimals = 1) %>% 
  cols_label(m = "Gjennomsnitt",
             sd = "±") %>% 
  mutate(m_s = paste0(signif(m, 5), " (", signif (s, 5), ") "))



```




```{r}




cyclingstudy %>%
        # select participant, time-point and VO2max
        select(subject, timepoint, VO2.max) %>%
        # Group the data frame by timepoint
  group_by(timepoint) %>% 
        
        # Summarise with mean and standard deviation for vo2max
        summarise(m = mean(VO2.max, na.rm = TRUE),
                  sd = sd(VO2.max, na.rm = TRUE)) %>% 
        # Print the results
        print()
```


### What is the average (mean) cmj.max height in group == "INCR" at timepoint == "meso2"?
What is the standard deviation of VO2.max at time-point meso3?

```{r}

cyclingstudy |> 
  select(group, cmj.max, timepoint, VO2.max) |> 
  group_by(timepoint, group) |> 
  summarise(gj.snitt.cmj.max = mean(cmj.max, na.rm = TRUE)) |> 
  filter(group == "INCR") |> 
  filter(timepoint == "meso2") |> 
    print()



```



```{r}

cyclingstudy |> 
  select(group, VO2.max, timepoint) |> 
  group_by(timepoint) |> 
  summarise(sd = sd(VO2.max, na.rm = TRUE)) |> 
  filter(timepoint == ("meso3")) |> 
  print()


```




```{r}

cyclingstudy |> 
  summarise(n = n(),
            .by = c(group, timepoint))




```




```{r}


cyclingstudy |> 
  select(group, age, height.T1, weight.T1, timepoint) |> 
  filter(timepoint == ("pre")) |> 
  summarise(.by = c(group),
            m.age = mean(age, na.rm = TRUE),
            sd.age = sd(age, na.rm = TRUE),
            m.height = mean(height.T1, na.rm = TRUE),
            sd.height = sd(height.T1, na.rm = TRUE),
            m.weight = mean(weight.T1, na.rm = TRUE),
            sd.weight = sd(weight.T1, na.rm = TRUE),
            n = n(),) |> 
  print()
  

```

### Pivot med forklaringer



```{r}

df |>  
  select(id, timepoint, la.max) |> 
  
  pivot_wider(names_from = timepoint,
              values_from = la.max) |> 
      pivot_longer(values_to = "la.max",
               names_to = "timepoint",
               cols = t3:t2) |> 
  arrange(timepoint) |> 


      print()




```


### Kalkuler typiske feil



```{r}



cv <- df |> 
  select(timepoint, id, la.max) |> 
  pivot_wider(names_from = timepoint,
              values_from = la.max) |> 
  print()
  
  mutate(diff = t2 - t1) |> 
  summarise(m = mean(c(t1, t2), na.rm = TRUE),
            s = sd(diff, na.rm = TRUE),
            te = s / sqrt(2),
            cv = 100 * (te/m)) |> 
  print()

  
cv_percent <-  round(cv$cv,1)
  print()





```



## Data in text

To add calculated numbers in text we can use `r`

The coefficient of variation was `cv_percent`
